# Generated by Django 4.1.1 on 2022-11-20 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number_alter_otp_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_receiver',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('3cc43ebe-8a1d-4fce-99a7-59f5975bc53f'), editable=False),
        ),
    ]
