# Generated by Django 4.1.1 on 2022-11-20 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_otp_email_remove_otp_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('3171538c-04e4-4fc8-9d5b-733325a7ee7b'), editable=False, unique=True),
        ),
    ]
