# Generated by Django 4.1.1 on 2022-11-20 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_otp_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('87aac1bc-0530-493c-b7c2-b18028dadcbb'), editable=False, unique=True),
        ),
    ]
