# Generated by Django 4.1.1 on 2022-11-20 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otp_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='request_id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('8b1917d1-71ff-4938-b9e8-2311edf0edf8'), editable=False),
        ),
    ]
