# Generated by Django 4.1.1 on 2022-12-02 13:43

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.IntegerField(default=accounts.utils.generate_otp),
        ),
    ]
